export {
  FOUNDATION_BOUNDARY,
  AUTH_LOGIN_COOKIE,
  AUTH_SESSION_COOKIE,
  AuthenticationError,
  type AuthCookie,
  type AuthProviderId,
  type AuthenticationPort,
  type AuthenticationErrorCode,
  type AuthenticatedIdentity,
  type ApplicationUser,
  type UserAccountStatus,
  type CompleteLoginInput,
  type CompleteLoginResult,
  type LogoutInput,
  type LogoutResult,
  type ReadSessionInput,
  type StartLoginResult,
  type AuthorizationPort,
  type AuthorizationRequest,
  type AuthorizationDecision,
  type AuthorizationContext,
  type AuthorizationDenyReason,
  FOUNDATION_PERMISSIONS,
  PATIENT_PERMISSIONS,
  APPOINTMENT_PERMISSIONS,
  NOTIFICATION_PERMISSIONS,
  APPLICATION_PERMISSIONS,
  PLATFORM_PERMISSIONS,
  isFoundationPermission,
  isPatientPermission,
  isAppointmentPermission,
  isNotificationPermission,
  isApplicationPermission,
  isPlatformPermission,
  type FoundationPermission,
  type PatientPermission,
  type AppointmentPermission,
  type NotificationPermission,
  type ApplicationPermission,
  type PlatformPermission,
  TENANT_ROLE_KEYS,
  PLATFORM_ROLE_KEYS,
  ROLE_KEYS,
  isTenantRoleKey,
  isPlatformRoleKey,
  isRoleKey,
  type TenantRoleKey,
  type PlatformRoleKey,
  type RoleKey,
} from "./foundation/index.js";
export {
  PATIENT_BOUNDARY,
  PATIENT_STATUSES,
  isPatientStatus,
  PatientValidationError,
  type Patient,
  type PatientStatus,
  type PatientCreateInput,
  type PatientUpdateInput,
  type PatientRepository,
} from "./patient/index.js";
export {
  APPOINTMENT_BOUNDARY,
  APPOINTMENT_STATUSES,
  ACTIVE_SCHEDULING_STATUSES,
  isAppointmentStatus,
  isActiveSchedulingStatus,
  canCancel,
  canReschedule,
  AppointmentValidationError,
  AppointmentConflictError,
  AppointmentTransitionError,
  AppointmentNotFoundError,
  APPOINTMENT_HISTORY_EVENTS,
  OUTBOX_EVENT_TYPES,
  type Appointment,
  type AppointmentStatus,
  type ActiveSchedulingStatus,
  type AppointmentCreateInput,
  type AppointmentRescheduleInput,
  type AppointmentListFilter,
  type Practitioner,
  type BranchRecord,
  type AppointmentHistoryRecord,
  type AppointmentHistoryEvent,
  type NotificationOutboxIntent,
  type OutboxEventType,
  type AppointmentRepository,
  type AppointmentWriteContext,
  type PractitionerRepository,
  type BranchLookup,
} from "./appointment/index.js";
export {
  NOTIFICATION_BOUNDARY,
  OUTBOX_STATUSES,
  isOutboxStatus,
  NOTIFICATION_MAX_ATTEMPTS,
  NOTIFICATION_RETRY_DELAYS_MS,
  NOTIFICATION_ERROR_CATEGORIES,
  type NotificationChannel,
  type NotificationDeliveryOutcome,
  type NotificationMessage,
  type NotificationDeliveryResult,
  type NotificationDeliveryPort,
  type OutboxStatus,
  type NotificationErrorCategory,
  type NotificationOutboxRecord,
  type OutboxClaimOptions,
  type NotificationAuditInput,
  type NotificationOutboxRepository,
} from "./notification/index.js";

export const DOMAIN_BOUNDARIES = ["foundation", "patient", "appointment", "notification"] as const;

export type DomainBoundary = (typeof DOMAIN_BOUNDARIES)[number];
