export {
  FOUNDATION_BOUNDARY,
  AUTH_LOGIN_COOKIE,
  AUTH_SESSION_COOKIE,
  AuthenticationError,
  type AuthCookie,
  type AuthProviderId,
  type AuthenticationPort,
  type AuthenticationErrorCode,
  type AuthenticatedIdentity,
  type ApplicationUser,
  type UserAccountStatus,
  type CompleteLoginInput,
  type CompleteLoginResult,
  type LogoutInput,
  type LogoutResult,
  type ReadSessionInput,
  type StartLoginResult,
  type AuthorizationPort,
  type AuthorizationRequest,
  type AuthorizationDecision,
  type AuthorizationContext,
  type AuthorizationDenyReason,
  FOUNDATION_PERMISSIONS,
  PATIENT_PERMISSIONS,
  APPOINTMENT_PERMISSIONS,
  NOTIFICATION_PERMISSIONS,
  PRACTITIONER_PERMISSIONS,
  IDENTITY_PERMISSIONS,
  APPLICATION_PERMISSIONS,
  PLATFORM_PERMISSIONS,
  isFoundationPermission,
  isPatientPermission,
  isAppointmentPermission,
  isNotificationPermission,
  isPractitionerPermission,
  isIdentityPermission,
  isApplicationPermission,
  isPlatformPermission,
  type FoundationPermission,
  type PatientPermission,
  type AppointmentPermission,
  type NotificationPermission,
  type PractitionerPermission,
  type IdentityPermission,
  type ApplicationPermission,
  type PlatformPermission,
  ADDRESS_TYPES,
  isAddressType,
  type AddressType,
  type Address,
  type AddressCreateInput,
  INVITATION_PURPOSES,
  INVITATION_STATUSES,
  CLINIC_CODE_STATUSES,
  isInvitationPurpose,
  isInvitationStatus,
  isClinicCodeStatus,
  type InvitationPurpose,
  type InvitationStatus,
  type OrganizationInvitation,
  type ClinicCodeStatus,
  type ClinicCode,
  OTP_DESTINATION_TYPES,
  OTP_PURPOSES,
  REGISTRATION_SESSION_STATUSES,
  isOtpDestinationType,
  isOtpPurpose,
  isRegistrationSessionStatus,
  type OtpDestinationType,
  type OtpPurpose,
  type AuthOtpChallenge,
  type RegistrationSessionStatus,
  type RegistrationSession,
  type AddressDraft,
  type PatientUserLink,
  type SmsDeliveryOutcome,
  type SmsMessage,
  type SmsDeliveryResult,
  type SmsDeliveryPort,
  TENANT_ROLE_KEYS,
  PLATFORM_ROLE_KEYS,
  ROLE_KEYS,
  isTenantRoleKey,
  isPlatformRoleKey,
  isRoleKey,
  type TenantRoleKey,
  type PlatformRoleKey,
  type RoleKey,
} from "./foundation/index.js";
export {
  PATIENT_BOUNDARY,
  PATIENT_STATUSES,
  isPatientStatus,
  PatientValidationError,
  type Patient,
  type PatientStatus,
  type PatientCreateInput,
  type PatientUpdateInput,
  type PatientRepository,
} from "./patient/index.js";
export {
  APPOINTMENT_BOUNDARY,
  APPOINTMENT_STATUSES,
  ACTIVE_SCHEDULING_STATUSES,
  TERMINAL_APPOINTMENT_STATUSES,
  CHECK_IN_LEAD_MS,
  APPOINTMENT_LIFECYCLE_COMMANDS,
  APPOINTMENT_LIFECYCLE_SPECS,
  isAppointmentStatus,
  isActiveSchedulingStatus,
  isTerminalAppointmentStatus,
  isAppointmentLifecycleCommand,
  canCancel,
  canReschedule,
  canApplyLifecycleCommand,
  AppointmentValidationError,
  AppointmentConflictError,
  AppointmentTransitionError,
  AppointmentNotFoundError,
  APPOINTMENT_HISTORY_EVENTS,
  OUTBOX_EVENT_TYPES,
  type Appointment,
  type AppointmentStatus,
  type ActiveSchedulingStatus,
  type TerminalAppointmentStatus,
  type AppointmentLifecycleCommand,
  type AppointmentCreateInput,
  type AppointmentRescheduleInput,
  type AppointmentListFilter,
  type Practitioner,
  type BranchRecord,
  type AppointmentHistoryRecord,
  type AppointmentHistoryEvent,
  type NotificationOutboxIntent,
  type OutboxEventType,
  type AppointmentRepository,
  type AppointmentWriteContext,
  type PractitionerRepository,
  type BranchLookup,
} from "./appointment/index.js";
export {
  NOTIFICATION_BOUNDARY,
  OUTBOX_STATUSES,
  isOutboxStatus,
  NOTIFICATION_MAX_ATTEMPTS,
  NOTIFICATION_RETRY_DELAYS_MS,
  NOTIFICATION_ERROR_CATEGORIES,
  type NotificationChannel,
  type NotificationDeliveryOutcome,
  type NotificationMessage,
  type NotificationDeliveryResult,
  type NotificationDeliveryPort,
  type OutboxStatus,
  type NotificationErrorCategory,
  type NotificationOutboxRecord,
  type OutboxClaimOptions,
  type NotificationAuditInput,
  type NotificationOutboxRepository,
} from "./notification/index.js";
export {
  PRACTITIONER_BOUNDARY,
  PRACTITIONER_STATUSES,
  PRACTITIONER_VERIFICATION_STATUSES,
  UNAVAILABILITY_KINDS,
  UNAVAILABILITY_STATUSES,
  WEEKDAYS,
  AVAILABILITY_UNAVAILABLE_REASONS,
  OPERATIONAL_CONFLICT_REASONS,
  PRACTITIONER_HISTORY_EVENTS,
  PRACTITIONER_AUDIT_ACTIONS,
  isPractitionerStatus,
  isPractitionerVerificationStatus,
  isUnavailabilityKind,
  isUnavailabilityStatus,
  isWeekday,
  PractitionerValidationError,
  PractitionerConflictError,
  PractitionerNotFoundError,
  evaluateAvailability,
  operationalConflicts,
  intervalsOverlap,
  subtractIntervals,
  mergeIntervals,
  weeklyIntervalsOverlap,
  assertIanaTimeZone,
  isValidIanaTimeZone,
  zonedParts,
  zonedLocalToUtc,
  type PractitionerStatus,
  type PractitionerVerificationStatus,
  type PractitionerCreateInput,
  type PractitionerUpdateInput,
  type PractitionerBranchAssignment,
  type UnavailabilityKind,
  type UnavailabilityStatus,
  type Weekday,
  type WeeklyWorkingInterval,
  type PractitionerSchedule,
  type PractitionerUnavailability,
  type PractitionerCreateScheduleInput,
  type WeeklyIntervalInput,
  type PractitionerReplaceScheduleInput,
  type PractitionerUnavailabilityCreateInput,
  type PractitionerAvailabilityQuery,
  type AvailabilityUnavailableReason,
  type OperationalConflictReason,
  type AvailableRange,
  type UnavailableRange,
  type OperationalConflict,
  type PractitionerAvailabilityResult,
  type PractitionerHistoryEvent,
  type PractitionerHistoryRecord,
  type PractitionerAuditAction,
  type PractitionerWriteContext,
  type PractitionerManagementRepository,
  type PractitionerAppointmentLookup,
  type UtcInterval,
  type AvailabilityAppointment,
  type EvaluateAvailabilityInput,
} from "./practitioner/index.js";

export const DOMAIN_BOUNDARIES = [
  "foundation",
  "patient",
  "appointment",
  "notification",
  "practitioner",
] as const;

export type DomainBoundary = (typeof DOMAIN_BOUNDARIES)[number];
